# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - "release-*"
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '*.md'

env:
  IMAGE_NAME: ${{ github.repository }}
  GONOPROXY: kubegems.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - uses: azure/setup-helm@v3
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Helm Package Push
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
          GIT_VERSION: ${{ github.ref_name }}
        run: make helm-push 

      # Cache go modules for faster builds
      # https://github.com/actions/cache/blob/main/examples.md#go---modules
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-

      # Build binary
      - name: Build binaries
        env:
          GIT_VERSION: ${{ github.ref_name }}
        run: make build

      # Build images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
#       - name: Log into registry ${{ env.SECONDARY_REGISTRY }}
#         if: github.event_name != 'pull_request'
#         uses: docker/login-action@v2.0.0
#         with:
#           registry: ${{ secrets.SECONDARY_REGISTRY }}
#           username: ${{ secrets.SECONDARY_REGISTRY_USERNAME }}
#           password: ${{ secrets.SECONDARY_REGISTRY_PASSWORD }}
      - name: Build Docker
        env: 
          GIT_VERSION: ${{ github.ref_name }}
          PUSH: ${{ github.event_name != 'pull_request' }}
        run: make docker
